import type { Metadata } from "next";
import { Gotu } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";

// Import Gotu from Google Fonts
const gotu = Gotu({
  subsets: ["latin"],
  variable: "--font-gotu",
  weight: ["400"], // Adjust weights as necessary
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gotu.variable} antialiased `}
      >
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
